export const authActionTypes = {
    AUTH_SET_TOKEN: "AUTH_SET_TOKEN",
    AUTH_CLEAR_TOKEN: "AUTH_CLEAR_TOKEN",
    AUTH_LOGIN_PENDING: "AUTH_LOGIN_PENDING",
    AUTH_LOGIN_SUCCESSFUL: "AUTH_LOGIN_SUCCESSFUL",
    AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
    AUTH_OTP_PENDING: "AUTH_OTP_PENDING",
    AUTH_OTP_SUCCESSFUL: "AUTH_OTP_SUCCESSFUL",
    AUTH_OTP_ERROR: "AUTH_OTP_ERROR"
};

