export const authActionTypes = {
    AUTH_LOGIN_PENDING: "AUTH_LOGIN_PENDING",
    AUTH_LOGIN_SUCCESSFUL: "AUTH_LOGIN_SUCCESSFUL",
    AUTH_INITIALIZED: "AUTH_INITIALIZED",
    AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR",
    AUTH_OTP_PENDING: "AUTH_OTP_PENDING",
    AUTH_OTP_SUCCESSFUL: "AUTH_OTP_SUCCESSFUL",
    AUTH_OTP_ERROR: "AUTH_OTP_ERROR",
    AUTH_FORGOT_PASSWORD_PENDING: "AUTH_FORGOT_PASSWORD_PENDING",
    AUTH_FORGOT_PASSWORD_SUCCESSFUL: "AUTH_FORGOT_PASSWORD_SUCCESSFUL",
    AUTH_FORGOT_PASSWORD_ERROR: "AUTH_FORGOT_PASSWORD_ERROR",
    AUTH_RESET_PASSWORD_PENDING: "AUTH_RESET_PASSWORD_PENDING",
    AUTH_RESET_PASSWORD_SUCCESSFUL: "AUTH_RESET_PASSWORD_SUCCESSFUL",
    AUTH_RESET_PASSWORD_ERROR: "AUTH_RESET_PASSWORD_ERROR",
    AUTH_RESET_UI: "AUTH_RESET_UI"
};

